-- ===========================================================
-- 字体本地化：font_family 九选项改为中文分类 + 指向打包字体
-- 配合 web/font/fonts.css（声明 FontHei/FontSong/... 字体族）
-- 幂等：整行 SET，可重复执行。
-- 说明：内部 value 键保持不变（display_geometric 等），仅改
--       显示名 label 为中文分类，避免已有卡片的 style_json 失效。
-- 执行：Supabase SQL Editor 全选执行；改完务必硬刷新页面重拉模板。
-- ===========================================================

UPDATE style_typo_options SET label='黑体', css_template='.gallery-card[data-style-typo-font-family-title="display_geometric"] .card-title{font-family:"FontHei","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-date="display_geometric"] .card-date{font-family:"FontHei","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-highlights="display_geometric"] .card-highlight-item{font-family:"FontHei","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-capsule="display_geometric"] .card-capsule{font-family:"FontHei","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-headertext="display_geometric"] .card-header-text{font-family:"FontHei","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-sidetext="display_geometric"] .card-side-text{font-family:"FontHei","PingFang SC","Microsoft YaHei",sans-serif;}' WHERE sub_dim='font_family' AND value='display_geometric';

UPDATE style_typo_options SET label='圆体', css_template='.gallery-card[data-style-typo-font-family-title="system_sans"] .card-title{font-family:"FontYuan","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-date="system_sans"] .card-date{font-family:"FontYuan","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-highlights="system_sans"] .card-highlight-item{font-family:"FontYuan","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-capsule="system_sans"] .card-capsule{font-family:"FontYuan","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-headertext="system_sans"] .card-header-text{font-family:"FontYuan","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-sidetext="system_sans"] .card-side-text{font-family:"FontYuan","PingFang SC","Microsoft YaHei",sans-serif;}' WHERE sub_dim='font_family' AND value='system_sans';

UPDATE style_typo_options SET label='宋体', css_template='.gallery-card[data-style-typo-font-family-title="editorial_serif"] .card-title{font-family:"FontSong","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-date="editorial_serif"] .card-date{font-family:"FontSong","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-highlights="editorial_serif"] .card-highlight-item{font-family:"FontSong","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-capsule="editorial_serif"] .card-capsule{font-family:"FontSong","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-headertext="editorial_serif"] .card-header-text{font-family:"FontSong","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-sidetext="editorial_serif"] .card-side-text{font-family:"FontSong","Songti SC","SimSun",serif;}' WHERE sub_dim='font_family' AND value='editorial_serif';

UPDATE style_typo_options SET label='楷体', css_template='.gallery-card[data-style-typo-font-family-title="rounded_soft"] .card-title{font-family:"FontKai","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-date="rounded_soft"] .card-date{font-family:"FontKai","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-highlights="rounded_soft"] .card-highlight-item{font-family:"FontKai","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-capsule="rounded_soft"] .card-capsule{font-family:"FontKai","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-headertext="rounded_soft"] .card-header-text{font-family:"FontKai","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-sidetext="rounded_soft"] .card-side-text{font-family:"FontKai","Songti SC","SimSun",serif;}' WHERE sub_dim='font_family' AND value='rounded_soft';

UPDATE style_typo_options SET label='创意', css_template='.gallery-card[data-style-typo-font-family-title="condensed_impact"] .card-title{font-family:"FontCreative","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-date="condensed_impact"] .card-date{font-family:"FontCreative","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-highlights="condensed_impact"] .card-highlight-item{font-family:"FontCreative","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-capsule="condensed_impact"] .card-capsule{font-family:"FontCreative","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-headertext="condensed_impact"] .card-header-text{font-family:"FontCreative","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-sidetext="condensed_impact"] .card-side-text{font-family:"FontCreative","PingFang SC","Microsoft YaHei",sans-serif;}' WHERE sub_dim='font_family' AND value='condensed_impact';

UPDATE style_typo_options SET label='书法', css_template='.gallery-card[data-style-typo-font-family-title="slab_serif"] .card-title{font-family:"FontCalli","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-date="slab_serif"] .card-date{font-family:"FontCalli","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-highlights="slab_serif"] .card-highlight-item{font-family:"FontCalli","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-capsule="slab_serif"] .card-capsule{font-family:"FontCalli","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-headertext="slab_serif"] .card-header-text{font-family:"FontCalli","Songti SC","SimSun",serif;}.gallery-card[data-style-typo-font-family-sidetext="slab_serif"] .card-side-text{font-family:"FontCalli","Songti SC","SimSun",serif;}' WHERE sub_dim='font_family' AND value='slab_serif';

UPDATE style_typo_options SET label='卡通', css_template='.gallery-card[data-style-typo-font-family-title="modern_sans"] .card-title{font-family:"FontCartoon","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-date="modern_sans"] .card-date{font-family:"FontCartoon","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-highlights="modern_sans"] .card-highlight-item{font-family:"FontCartoon","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-capsule="modern_sans"] .card-capsule{font-family:"FontCartoon","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-headertext="modern_sans"] .card-header-text{font-family:"FontCartoon","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-sidetext="modern_sans"] .card-side-text{font-family:"FontCartoon","PingFang SC","Microsoft YaHei",sans-serif;}' WHERE sub_dim='font_family' AND value='modern_sans';

UPDATE style_typo_options SET label='手写', css_template='.gallery-card[data-style-typo-font-family-title="handwritten_note"] .card-title{font-family:"FontHand","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-date="handwritten_note"] .card-date{font-family:"FontHand","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-highlights="handwritten_note"] .card-highlight-item{font-family:"FontHand","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-capsule="handwritten_note"] .card-capsule{font-family:"FontHand","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-headertext="handwritten_note"] .card-header-text{font-family:"FontHand","PingFang SC","Microsoft YaHei",sans-serif;}.gallery-card[data-style-typo-font-family-sidetext="handwritten_note"] .card-side-text{font-family:"FontHand","PingFang SC","Microsoft YaHei",sans-serif;}' WHERE sub_dim='font_family' AND value='handwritten_note';

UPDATE style_typo_options SET label='等宽', css_template='.gallery-card[data-style-typo-font-family-title="terminal_mono"] .card-title{font-family:"FontMono","Cascadia Code",Consolas,Menlo,monospace;}.gallery-card[data-style-typo-font-family-date="terminal_mono"] .card-date{font-family:"FontMono","Cascadia Code",Consolas,Menlo,monospace;}.gallery-card[data-style-typo-font-family-highlights="terminal_mono"] .card-highlight-item{font-family:"FontMono","Cascadia Code",Consolas,Menlo,monospace;}.gallery-card[data-style-typo-font-family-capsule="terminal_mono"] .card-capsule{font-family:"FontMono","Cascadia Code",Consolas,Menlo,monospace;}.gallery-card[data-style-typo-font-family-headertext="terminal_mono"] .card-header-text{font-family:"FontMono","Cascadia Code",Consolas,Menlo,monospace;}.gallery-card[data-style-typo-font-family-sidetext="terminal_mono"] .card-side-text{font-family:"FontMono","Cascadia Code",Consolas,Menlo,monospace;}' WHERE sub_dim='font_family' AND value='terminal_mono';
