-- 由 parse_style_pool.py 自动生成
-- 将 card_css 反向解析为 style_json

UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "code_header", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "industrial", "typo": {"title": "mono", "date": "mono", "body": "mono"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "none", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 C 语言代码 的 card_css 反向解析生成"}'::jsonb WHERE id = 3;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "mono", "date": "mono", "body": "mono"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "none", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 JavaScript 代码 的 card_css 反向解析生成"}'::jsonb WHERE id = 5;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "industrial", "typo": {"title": "mono", "date": "mono", "body": "mono"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 SQL 查询 的 card_css 反向解析生成"}'::jsonb WHERE id = 7;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "code_header", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "industrial", "typo": {"title": "mono", "date": "mono", "body": "mono"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "none", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 XML 文档 的 card_css 反向解析生成"}'::jsonb WHERE id = 9;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "default", "date": "default", "body": "default"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 合同协议 的 card_css 反向解析生成"}'::jsonb WHERE id = 23;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "serif", "date": "mono", "body": "serif"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 发票 的 card_css 反向解析生成"}'::jsonb WHERE id = 27;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "sans", "date": "sans", "body": "sans"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "tilt"}, "_comment": "由 购物清单 的 card_css 反向解析生成"}'::jsonb WHERE id = 33;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "avatar_left", "overlay": "none"}, "palette": "warm", "typo": {"title": "sans", "date": "sans", "body": "sans"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 微信聊天记录 的 card_css 反向解析生成"}'::jsonb WHERE id = 50;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "sans", "date": "sans", "body": "sans"}, "border": {"style": "none", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "tilt"}, "_comment": "由 手抄报 的 card_css 反向解析生成"}'::jsonb WHERE id = 68;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "default", "date": "default", "body": "default"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "none", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 红头文件 的 card_css 反向解析生成"}'::jsonb WHERE id = 75;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "code_header", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "industrial", "typo": {"title": "mono", "date": "mono", "body": "mono"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "none", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 CSS 样式表 的 card_css 反向解析生成"}'::jsonb WHERE id = 82;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "mono", "date": "mono", "body": "mono"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "ecg_wave"}, "_comment": "由 心电图 的 card_css 反向解析生成"}'::jsonb WHERE id = 97;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "industrial", "typo": {"title": "mono", "date": "mono", "body": "mono"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "none", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 股票 K 线图 的 card_css 反向解析生成"}'::jsonb WHERE id = 99;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "serif", "date": "serif", "body": "serif"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 绕口令 的 card_css 反向解析生成"}'::jsonb WHERE id = 106;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "sans", "date": "sans", "body": "sans"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "none", "animation": "none"}, "_comment": "由 网络用语 的 card_css 反向解析生成"}'::jsonb WHERE id = 121;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "default", "date": "default", "body": "default"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 倒写 的 card_css 反向解析生成"}'::jsonb WHERE id = 134;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "mono", "date": "mono", "body": "mono"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 时间 的 card_css 反向解析生成"}'::jsonb WHERE id = 148;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "default", "date": "default", "body": "default"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 正剧 的 card_css 反向解析生成"}'::jsonb WHERE id = 210;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "default", "date": "default", "body": "default"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 剧本 的 card_css 反向解析生成"}'::jsonb WHERE id = 213;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "mono", "date": "mono", "body": "mono"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 索引 的 card_css 反向解析生成"}'::jsonb WHERE id = 227;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "sans", "date": "sans", "body": "sans"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 色卡比对 的 card_css 反向解析生成"}'::jsonb WHERE id = 262;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "sans", "date": "sans", "body": "sans"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 心理咨询师个案 的 card_css 反向解析生成"}'::jsonb WHERE id = 265;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "industrial", "typo": {"title": "mono", "date": "mono", "body": "mono"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 DJ 打碟歌单 的 card_css 反向解析生成"}'::jsonb WHERE id = 271;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "mono", "date": "mono", "body": "mono"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 404 Not Found 的 card_css 反向解析生成"}'::jsonb WHERE id = 296;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "mono", "date": "mono", "body": "mono"}, "border": {"style": "none", "accent": false}, "deco": {"title": "none", "separator": "text_line", "footer": "none"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 自动售货机清单 的 card_css 反向解析生成"}'::jsonb WHERE id = 298;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "default", "date": "default", "body": "default"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 鲁迅 的 card_css 反向解析生成"}'::jsonb WHERE id = 306;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "default", "date": "default", "body": "default"}, "border": {"style": "none", "accent": false}, "deco": {"title": "none", "separator": "none", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 芥川龙之介 的 card_css 反向解析生成"}'::jsonb WHERE id = 308;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "default", "date": "default", "body": "default"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "tilt"}, "_comment": "由 马尔克斯 的 card_css 反向解析生成"}'::jsonb WHERE id = 309;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "default", "date": "default", "body": "default"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "none", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 陀思妥耶夫斯基 的 card_css 反向解析生成"}'::jsonb WHERE id = 311;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "default", "date": "default", "body": "default"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 三岛由纪夫 的 card_css 反向解析生成"}'::jsonb WHERE id = 313;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "default", "date": "default", "body": "default"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "none", "separator": "text_line", "footer": "none"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 菲茨杰拉德 的 card_css 反向解析生成"}'::jsonb WHERE id = 316;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "serif", "date": "serif", "body": "serif"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "none", "separator": "text_line", "footer": "none"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 莫言 的 card_css 反向解析生成"}'::jsonb WHERE id = 321;
UPDATE "STYLE_POOL" SET style_json = '{"layout": {"top": "title_only", "body": "highlight_list", "bottom": "meta_line", "side": "none", "overlay": "none"}, "palette": "warm", "typo": {"title": "default", "date": "default", "body": "default"}, "border": {"style": "solid", "accent": false}, "deco": {"title": "prefix_suffix", "separator": "text_line", "footer": "capsule_name"}, "effect": {"hover": "lift", "animation": "none"}, "_comment": "由 雨果 的 card_css 反向解析生成"}'::jsonb WHERE id = 325;
